spring.application.name=case2
server.port=8082

case2.camunda.engine-rest-url=${CAMUNDA_ENGINE_REST_URL:http://192.168.111.3:8080/engine-rest}
case2.camunda.username=${CAMUNDA_USERNAME:group4}
case2.camunda.password=${CAMUNDA_PASSWORD:PLVbIZynDiaW6K}
case2.camunda.topic=${CASE2_CAMUNDA_TOPIC:group4_decision}
case2.camunda.shipping-topic=${CASE2_CAMUNDA_SHIPPING_TOPIC:group4_rest}
case2.spedition.base-url=${SPEDITION_BASE_URL:http://192.168.111.5:8080/v1}
case2.spedition.request-path=${SPEDITION_REQUEST_PATH:/consignment/request}

spring.datasource.url=${CASE2_DB_URL:jdbc:mysql://192.168.111.4:3306/db_group4?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${CASE2_DB_USERNAME:group4}
spring.datasource.password=${CASE2_DB_PASSWORD:ala3d3adqa3ed0x4}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always

management.endpoints.web.exposure.include=health,info,metrics,prometheus

logging.level.root=INFO
logging.level.com.group4.case2=INFO
logging.level.org.camunda.bpm.client=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [task=%X{taskId} proc=%X{procInstId} exec=%X{executionId}] %logger{36} - %msg%n
