[Interface]
PrivateKey = qAjZBX2wfmd1gSVlG+GsKrXvv9SKske8alAQu7/Y31w=
Address = 192.168.111.139/24

[Peer]
PublicKey = DKANtdTQgC0hvZyeNyJckxPO+8s/NRkUMz8hM6fRVy0=
AllowedIPs = 192.168.111.0/24
Endpoint = vpn.fhnw.i.schaaf.es:51820
